### ISSUE TITLE
Peer to peer code review on homepage

### ISSUE THREAD

**Issue by Chandan-devs-tech** [helina42/Portfolio#7]
Hi @helina42 
- Good job so far you have done! 
- There are some changes required to make your portfolio look better.
# Required Changes ♻️ 

- Please give your background image size should be 100%
- Please reduce the top and bottom margin to make your portfolio look better.

<img width="947" alt="helina1" src="https://user-images.githubusercontent.com/65088027/223355731-3f9d88b7-8a71-45a7-b937-a57f1783e9d6.png">

<img src="https://media0.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

**Comment by helina42** [comment]
Thank you for your comment! 😃
